# docker-compose.yml

services:

  challengeapp:
    restart: unless-stopped
    container_name: challengeapp
    build:
      context: ./
      # dockerfile: ./Dockerfile

    volumes:
      - .:/var/www/html

    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_VERSION: ${APP_VERSION}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: dbmysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

    ports:
      - "8080:80"

    networks:
      - network-challengeapp

    depends_on:
      - dbmysql


  dbmysql:
    image: mysql

    ports:
      - "3307:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

    volumes:
      - db:/var/lib/mysql
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - network-challengeapp


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: dbmysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    ports:
      - "8090:80"

    depends_on:
      - dbmysql

    networks:
      - network-challengeapp

volumes:
  db:


networks:
  network-challengeapp:
    driver: bridge